### ISSUE TITLE
Os x install gives QtCore error

### ISSUE THREAD

**Issue by fotiDim** [Floobits/node-native-dmp#1]
Installing on OS X gives an error. This is the output:

npm http GET https://registry.npmjs.org/native-diff-match-patch
npm http 304 https://registry.npmjs.org/native-diff-match-patch

> native-diff-match-patch@0.0.3 preinstall /Users/fotis/node_modules/native-diff-match-patch
> node-gyp clean || (exit 0); node-gyp configure build

  CXX(target) Release/obj.target/dmp-test/src/diff_match_patch_test.o
../src/diff_match_patch_test.cpp:24:10: fatal error: 'QtCore' file not found
# include <QtCore>

```
     ^
```

1 error generated.
make: **\* [Release/obj.target/dmp-test/src/diff_match_patch_test.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/fotis/node_modules/native-diff-match-patch
gyp ERR! node -v v0.10.12
gyp ERR! node-gyp -v v0.10.0
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by ggreer** [comment]
The C++ version of diff-match-patch depends on QT. We need to document dependencies like that.

I recommend waiting a week or so before trying to use this module. There's a lot of cleaning up to be done.

**Comment by BorePlusPlus** [comment]
Hello, 

This is still an issue. Just to keep you on your toes. ;)

**Comment by ggreer** [comment]
If you've brew installed qt, this should work now. There was an issue with include paths.
